import React from "react";
import Sidebar from "./sidebars/Sidebar";
import Image from "next/image";
import AudioPlayer from "./sidebars/AudioPlayer";
import TableOfContentsServer from "./sidebars/TableOfContentsServer";
import RightSideBottom from "./sidebars/RightSideBottom";
import RightSideTop from "./sidebars/RightSideTop";
import Toc from "./Toc";

export default function BlogTemplate() {
  return (
    <div className="section panel mr-5">
      <div className="container container-full mx-3">
        <div className="panel py-4 lg:py-6 xl:py-8">
          <div className="row child-cols-12 ">
            <div className="sm:col-12 md:col-12 lg:col-6 order-1">
              <div
                className="uc-main panel"
                role="main"
                style={{ minHeight: "120vh" }}
              >
                <div className="panel vstack gap-3 lg:gap-4 xl:gap-5 mr-3">
                  
                  <p className="fs-6 md:fs-5">
                    Google hosted its annual I/O developer conference last Tuesday and introduced a series of artificial intelligence products. These include new search and chat features and AI hardware for cloud customers, underlining Google's insistence on AI even as rivals like OpenAI emerge.
                  </p>
                  
                  <h2 className="h4 sm:h3">Transforming Search with AI Overviews</h2>
                  <p className="fs-6 md:fs-5">
                    The switch from traditional results based on links to summaries generated by AI reveals a step towards a more intuitive and integrated search experience. Many industry experts have referred to this as the 'day zero' of Google search, the information retrieval technology that makes it easy for users to get quick insights into complex topics without having them move away from their initial queries.
                  </p>
                  <p className="fs-6 md:fs-5">
                    Generative AI significantly shifts from traditional keyword-based searching towards more intuitive, context-aware methods. It can generate and comprehend text that sounds human-like, so users get a comprehensive overview of their search queries immediately.
                  </p>
                  <p className="fs-6 md:fs-5">
                    With the help of Gemini, Google's latest AI model, they aim to revolutionize users' interaction with search results. To start, Google has introduced AI Overviews (earlier Google SGE), which essentially provides a summary of search results with links for further details, transforming how users search for information on Google.
                  </p>
                  <p className="fs-6 md:fs-5">
                    Building on the capabilities introduced with SGE, Google is pushing the boundaries of AI in search, making it faster, more precise, and exceptionally user-friendly. As AI Overviews roll out to users in the United States with plans for global expansion, casual users and professionals in fields like marketing should notice.
                  </p>
                  
                  <h2 className="h4 sm:h3">What Are Google's AI Overviews?</h2>
                  <p className="fs-6 md:fs-5">
                    AI Overviews is a new Google search feature that uses generative AI to create quick answers to search queries through a topic preview with links to learn more. Powered by Google Gemini, it combines information from multiple online sources to save the searcher time and provide a general overview – hence the name.
                  </p>
                  
                  <h3 className="h5 sm:h4">Example and Rollout</h3>
                  <p className="fs-6 md:fs-5">
                    As announced on May 14th, Google began rolling out AI Overviews to US-based searchers, with plans to expand to other countries. Originally introduced as part of the Google Search Labs experiment, Search Generative Experience (SGE), users had to opt into this feature. By the end of 2024, AI Overviews will be available to over a billion searchers.
                  </p>
                  
                  <h2 className="h4 sm:h3">How Do AI Overviews Work?</h2>
                  <p className="fs-6 md:fs-5">
                    Here's a general model of how AI Overviews generate responses:
                  </p>
                  
                  <h3 className="h5 sm:h4">Query Processing</h3>
                  <p className="fs-6 md:fs-5">
                    Once you type in a query, the AI transforms your words into a vector, just as ChatGPT works.
                  </p>
                  
                  <h3 className="h5 sm:h4">Document Selection</h3>
                  <p className="fs-6 md:fs-5">
                    Google's algorithm selects a few relevant web pages containing information related to the generated response.
                  </p>
                  
                  <h3 className="h5 sm:h4">Fact-Checking</h3>
                  <p className="fs-6 md:fs-5">
                    These chosen documents act as fact-checkers. If there is any contradiction between the AI-generated text and the information provided in these documents, then the AI modifies its response accordingly. Hence, you can see the "sources" mentioned each time.
                  </p>
                  
                  <h3 className="h5 sm:h4">Evaluation</h3>
                  <p className="fs-6 md:fs-5">
                    An extra evaluation step might be required to determine the response's accuracy and relevance before presenting it.
                  </p>
                  
                  <h2 className="h4 sm:h3">The Impact of AI Overviews on SEO So Far</h2>
                  <p className="fs-6 md:fs-5">
                    At one point, an AI summary was produced by about 85% of search queries. However, this trend has undoubtedly reversed, and at present, approximately 14% of searches produce an AI Summary. The likelihood of triggering an AI summary varies considerably across domains, fluctuating between 1% and 25%.
                  </p>
                  
                  <h3 className="h5 sm:h4">User Concerns</h3>
                  <p className="fs-6 md:fs-5">
                    Currently, users cannot opt out of AI Overviews, leading to frustration among some who have flooded Google's help forums for advice on disabling them. The Google trends chart for "turn off Google AI" spiked over the week that AI Overviews were launched, highlighting widespread discontent.
                  </p>
                  <p className="fs-6 md:fs-5">
                    Given the scale of its release and the extensive amount of Search Engine Results Page ("SERP") real estate it takes up, SEO professionals are concerned about how it will impact their organic rankings and overall SEO performance.
                  </p>
                  
                  <h3 className="h5 sm:h4">Concerns for Publishers</h3>
                  <p className="fs-6 md:fs-5">
                    Traditional page views may be adversely affected when AI Overviews consolidate content, leading to decreased ad revenue and lower content engagement. Based on habits that emerged during the past year's testing phase of Google's AI overviews, about 25% of the traffic could be negatively affected by the de-emphasis on website links, said Marc McCollum, chief innovation officer at Raptive.
                  </p>
                  
                  <h3 className="h5 sm:h4">Transactional Keywords and Local Intent</h3>
                  <p className="fs-6 md:fs-5">
                    In some cases, AI Overviews may be seen for longer-tail queries with transactional intent but only sometimes for short-tail ones. AI Overviews no longer show for local queries based on our sample. However, this might change in the future.
                  </p>
                  
                  <h3 className="h5 sm:h4">Informational Keywords are Most Affected</h3>
                  <p className="fs-6 md:fs-5">
                    AI overviews are mainly triggered by informational searches, especially those related to procedures or tasks.
                  </p>
                  
                  <h3 className="h5 sm:h4">Authoritative Domains</h3>
                  <p className="fs-6 md:fs-5">
                    AI Overviews are available for authoritative domains such as health, legal, and finance. However, they often come with the recommendation to consult experts in the field and to use the advice at the user's own risk.
                  </p>
                  
                  <h2 className="h4 sm:h3">Why Are AI Overviews So Limited?</h2>
                  <p className="fs-6 md:fs-5">
                    The limited appearance of AI overviews suggests some hesitation from Google in launching a full-scale implementation. Potential reasons include:
                  </p>
                  <p className="fs-6 md:fs-5">
                    Intent mismatch between search queries and AI Overviews. Fewer filters and features compared to traditional search results.
                  </p>
                  
                  <h2 className="h4 sm:h3">Embracing LLM SEO or Generative Engine Optimization</h2>
                  <p className="fs-6 md:fs-5">
                    LLM SEO / GEO revolves around content optimization for generative engines, which makes it vital for any content creator who desires to succeed in an AI-dominated search scene. Content creators can significantly increase the visibility of their content in artificial intelligence-based searches by employing LLM SEO/GEO strategies.
                  </p>
                  <p className="fs-6 md:fs-5">
                    If you want to learn more about this topic, check out the LLM SEO LeaderBoard. It covers almost all the techniques and hacks that are currently available.
                  </p>
                  
                  <h3 className="h5 sm:h4">AI Monitor Tracker</h3>
                  <p className="fs-6 md:fs-5">
                    With AI Monitor, you can track how frequently your content appears not only in AI overviews but also on other platforms such as ChatGPT, Perplexity, and others. After adding your website and setting up tracking for your selected prompts, the tool will begin monitoring your site's visibility across nearly every LLM-powered search engine.
                  </p>
                  
                  <h3 className="h5 sm:h4">Brand Mentions</h3>
                  <p className="fs-6 md:fs-5">
                    AI Monitor Brand Mentions is a fantastic tool for tracking brand mentions in AI summaries across various platforms. It's like having a spotlight on your content, even if it's not ranking high traditionally.
                  </p>
                  
                  <h3 className="h5 sm:h4">AI Semantic Rating</h3>
                  <p className="fs-6 md:fs-5">
                    In addition to the above, we help marketers track whether AI summaries portray your company as a hero or a villain in a fairytale. AI Monitor analyzes sentiment in AI summaries to ensure that your content is accurately portrayed.
                  </p>
                  
                  <h3 className="h5 sm:h4">LLM Click Rate</h3>
                  <p className="fs-6 md:fs-5">
                    We have also invented a novel framework for analyzing website prominence in AI summaries. Here, we present the "LLM Click Rate (LCR)" score, which is based on several significant metrics weighed by their importance in showing the true exposure of the website within LSE responses.
                  </p>
                  
                  <h2 className="h4 sm:h3">Conclusion</h2>
                  <p className="fs-6 md:fs-5">
                    The key point is: don't panic. Most AI responses are aimed at less common, less searched-for queries, which are generally unlikely to have a significant impact on most sites.
                  </p>
                  <p className="fs-6 md:fs-5">
                    Why stress about your website's SEO when you could prioritize these vital queries for your site instead? If you notice AI Overviews appearing for specific queries, aim to become one of the featured sources.
                  </p>
                  <p className="fs-6 md:fs-5">
                    If you want to learn more about how to feature your content or brand on LLM-powered search engines, check out the LLM SEO LeaderBoard, which covers almost all the techniques and hacks known to mankind.
                  </p>
                  
                  <h2 className="h4 sm:h3">Introduction to Modern Web Development</h2>
                  <p className="fs-6 md:fs-5">
                    This is placeholder paragraph text under heading one.
                    Replace this with your actual content. This is placeholder
                    paragraph text under heading one. Replace this with your
                    actual content. This is placeholder paragraph text under
                    heading one. Replace this with your actual content.
                  </p>
                  
                  <h3 className="h5 sm:h4">Getting Started with React</h3>
                  <p className="fs-6 md:fs-5">
                    Learn the fundamentals of React development and component architecture.
                  </p>
                  
                  <h3 className="h5 sm:h4">Setting Up Your Development Environment</h3>
                  <p className="fs-6 md:fs-5">
                    Essential tools and configurations for modern web development.
                  </p>
                  
                  <h2 className="h4 sm:h3">Advanced JavaScript Concepts</h2>
                  <p className="fs-6 md:fs-5">
                    Another short paragraph to demonstrate structure. Keep
                    sentences concise and readable.
                  </p>
                  
                  <h3 className="h5 sm:h4">Asynchronous Programming</h3>
                  <p className="fs-6 md:fs-5">
                    Understanding promises, async/await, and handling asynchronous operations.
                  </p>
                  
                  <h3 className="h5 sm:h4">ES6+ Features</h3>
                  <p className="fs-6 md:fs-5">
                    Modern JavaScript features including destructuring, arrow functions, and modules.
                  </p>
                  
                  <h3 className="h5 sm:h4">Error Handling Best Practices</h3>
                  <p className="fs-6 md:fs-5">
                    Strategies for robust error handling in JavaScript applications.
                  </p>
                  
                  <h2 className="h4 sm:h3">Performance Optimization</h2>
                  <p className="fs-6 md:fs-5">
                    Add notes, explanations, or examples that support the
                    heading above.
                  </p>
                  
                  <h3 className="h5 sm:h4">Code Splitting and Lazy Loading</h3>
                  <p className="fs-6 md:fs-5">
                    Techniques to improve application load times and user experience.
                  </p>
                  <h2 className="h4 sm:h3">Testing and Quality Assurance</h2>
                  <p className="fs-6 md:fs-5">
                    Continue with more placeholder copy. You can later swap
                    these with real text.
                  </p>
                  
                  <h3 className="h5 sm:h4">Unit Testing Fundamentals</h3>
                  <p className="fs-6 md:fs-5">
                    Writing effective unit tests for JavaScript applications.
                  </p>
                  
                  <h3 className="h5 sm:h4">Integration Testing Strategies</h3>
                  <p className="fs-6 md:fs-5">
                    Testing component interactions and API integrations.
                  </p>
                  
                  <h2 className="h4 sm:h3">Deployment and DevOps</h2>
                  <p className="fs-6 md:fs-5">
                    Maintain consistent styles for headings and paragraphs
                    across the template.
                  </p>
                  
                  <h3 className="h5 sm:h4">CI/CD Pipeline Setup</h3>
                  <p className="fs-6 md:fs-5">
                    Automating your deployment process with continuous integration.
                  </p>
                  
                  <h3 className="h5 sm:h4">Container Orchestration</h3>
                  <p className="fs-6 md:fs-5">
                    Managing applications with Docker and Kubernetes.
                  </p>
                  
                  <h2 className="h4 sm:h3">Security Best Practices</h2>
                  <p className="fs-6 md:fs-5">
                    Use this section for additional details, steps, or guidance
                    relevant to your topic.
                  </p>
                  
                  <h3 className="h5 sm:h4">Authentication and Authorization</h3>
                  <p className="fs-6 md:fs-5">
                    Implementing secure user authentication systems.
                  </p>
                  <h2 className="h4 sm:h3">Sample Heading Seven</h2>
                  <p className="fs-6 md:fs-5">
                    Placeholder text provides layout clarity before final
                    content is ready.
                  </p>
                  <h2 className="h4 sm:h3">Sample Heading Eight</h2>
                  <p className="fs-6 md:fs-5">
                    Replace with your final copy. Remove any sections you do not
                    need.
                  </p>
                  <h2 className="h4 sm:h3 m-0">Sample Heading Nine</h2>
                  <p className="fs-6 md:fs-5 m-0">
                    Final example paragraph to complete the template section
                    with nine headings.
                  </p>
                  <h2 className="h4 sm:h3 mt-3">Sample Heading Ten</h2>
                  <p className="fs-6 md:fs-5">
                    Short descriptive paragraph for heading ten. Replace with
                    your finalized wording.
                  </p>
                  <h2 className="h4 sm:h3">Sample Heading Eleven</h2>
                  <p className="fs-6 md:fs-5">
                    Keep paragraphs consistent in tone and length to improve
                    readability across sections.
                  </p>
                  <h2 className="h4 sm:h3">Sample Heading Twelve</h2>
                  <p className="fs-6 md:fs-5">
                    This area can include examples, definitions, or clarifying
                    notes related to the topic.
                  </p>
                  <h2 className="h4 sm:h3">Sample Heading Thirteen</h2>
                  <p className="fs-6 md:fs-5">
                    Use headings to break content into scannable sections,
                    making it easier to navigate.
                  </p>
                  <h2 className="h4 sm:h3">Sample Heading Fourteen</h2>
                  <p className="fs-6 md:fs-5">
                    You can also insert lists, links, or callouts here as needed
                    for your content strategy.
                  </p>
                  <h2 className="h4 sm:h3">Sample Heading Fifteen</h2>
                  <p className="fs-6 md:fs-5">
                    Consider keeping each paragraph focused on one idea to aid
                    comprehension.
                  </p>
                  <h2 className="h4 sm:h3">Sample Heading Sixteen</h2>
                  <p className="fs-6 md:fs-5">
                    Placeholder copy ensures layout fidelity before the final
                    content is ready.
                  </p>
                  <h2 className="h4 sm:h3">Sample Heading Seventeen</h2>
                  <p className="fs-6 md:fs-5">
                    Swap these samples with production content when available,
                    and adjust spacing as needed.
                  </p>
                  <h2 className="h4 sm:h3">Sample Heading Eighteen</h2>
                  <p className="fs-6 md:fs-5">
                    Maintain semantic structure by using heading levels in
                    descending order when appropriate.
                  </p>
                  <h2 className="h4 sm:h3">Sample Heading Nineteen</h2>
                  <p className="fs-6 md:fs-5">
                    Ensure accessibility by writing clear, descriptive headings
                    that summarize the section.
                  </p>
                  <h2 className="h4 sm:h3">Sample Heading Twenty</h2>
                  <p className="fs-6 md:fs-5">
                    This template can be adapted for tutorials, announcements,
                    or long-form articles.
                  </p>
                  <h2 className="h4 sm:h3">Sample Heading Twenty-One</h2>
                  <p className="fs-6 md:fs-5">
                    Keep visual rhythm with consistent spacing between headings
                    and paragraphs.
                  </p>
                  <h2 className="h4 sm:h3">Sample Heading Twenty-Two</h2>
                  <p className="fs-6 md:fs-5">
                    Use concise language and avoid jargon to make content
                    approachable for all readers.
                  </p>
                  <h2 className="h4 sm:h3">Sample Heading Twenty-Three</h2>
                  <p className="fs-6 md:fs-5">
                    Provide context and supporting details that help readers act
                    on the information.
                  </p>
                  <h2 className="h4 sm:h3">Sample Heading Twenty-Four</h2>
                  <p className="fs-6 md:fs-5">
                    If sections become long, consider adding subheadings or
                    bullet lists for clarity.
                  </p>
                  <h2 className="h4 sm:h3">Sample Heading Twenty-Five</h2>
                  <p className="fs-6 md:fs-5">
                    Align content with your brand voice and style guidelines for
                    consistency.
                  </p>
                  <h2 className="h4 sm:h3 m-0">Sample Heading Twenty-Six</h2>
                  <p className="fs-6 md:fs-5 m-0">
                    Final placeholder paragraph. Replace or trim as necessary
                    for your use case.
                  </p>
                </div>
              </div>
            </div>
            <div className="d-none lg:d-block lg:col-3 order-2 lg:order-0 sticky-element3">
              <AudioPlayer />
              <TableOfContentsServer />
            </div>
            <div className="d-none lg:d-block lg:col-3 order-2 lg:order-2 sticky-element3">
              <RightSideTop />
              <RightSideBottom />
            </div>
            <div className="d-block lg:d-none">
              <Toc />
            </div>
          </div>
          {/* <hr className="w-100 m-0 d-block mt-4 lg:mt-6 xl:mt-8" /> */}
          <div className="post-footer panel vstack sm:hstack gap-3 justify-between justifybetween border-top py-4 mt-4">
            <ul className="nav-x gap-narrow text-primary">
              <li>
                <span className="text-black dark:text-white me-narrow">
                  Tags:
                </span>
              </li>
              <li>
                <a href="#" className="gap-0">
                  Marketing
                  <span className="text-black dark:text-white">,</span>
                </a>
              </li>
              <li>
                <a href="#" className="gap-0">
                  Strategies
                  <span className="text-black dark:text-white">,</span>
                </a>
              </li>
              <li>
                <a href="#" className="gap-0">
                  Boost <span className="text-black dark:text-white">,</span>
                </a>
              </li>
              <li>
                <a href="#" className="gap-0">
                  Business
                </a>
              </li>
            </ul>
            <ul className="post-share-icons nav-x gap-narrow">
              <li className="me-1">
                <span className="text-black dark:text-white">Share:</span>
              </li>
              <li>
                <a
                  className="btn btn-md btn-outline-gray-100 w-32px lg:w-40px h-32px lg:h-40px text-dark dark:text-white dark:border-gray-600 hover:bg-primary hover:border-primary hover:text-white rounded-circle"
                  href="#"
                >
                  <i className="unicon-logo-facebook icon-1" />
                </a>
              </li>
              <li>
                <a
                  className="btn btn-md btn-outline-gray-100 w-32px lg:w-40px h-32px lg:h-40px text-dark dark:text-white dark:border-gray-600 hover:bg-primary hover:border-primary hover:text-white rounded-circle"
                  href="#"
                >
                  <i className="unicon-logo-x-filled icon-1" />
                </a>
              </li>
              <li>
                <a
                  className="btn btn-md btn-outline-gray-100 w-32px lg:w-40px h-32px lg:h-40px text-dark dark:text-white dark:border-gray-600 hover:bg-primary hover:border-primary hover:text-white rounded-circle"
                  href="#"
                >
                  <i className="unicon-email icon-1" />
                </a>
              </li>
              <li>
                <a
                  className="btn btn-md btn-outline-gray-100 w-32px lg:w-40px h-32px lg:h-40px text-dark dark:text-white dark:border-gray-600 hover:bg-primary hover:border-primary hover:text-white rounded-circle"
                  href="#"
                >
                  <i className="unicon-link icon-1" />
                </a>
              </li>
            </ul>
          </div>
        </div>
      </div>
    </div>
  );
}
