"use client";
import React from "react";
import Sidebar from "./sidebars/Sidebar";
import Image from "next/image";
import AudioPlayer from "./sidebars/AudioPlayer";
import TableOfContentsServer from "./sidebars/TableOfContentsServer";
import RightSideBottom from "./sidebars/RightSideBottom";
import RightSideTop from "./sidebars/RightSideTop";
import { Gallery, Item } from "react-photoswipe-gallery";
import Link from "next/link";

export default function WhatWeKnowAboutGoogleAIOverview() {
  return (
    <div className="section panel mr-5">
      <div className="container container-full mx-3">
        <div className="panel py-4 lg:py-6 xl:py-8">
          <div className="row child-cols-12 ">
            <div className="sm:col-12 md:col-12 lg:col-6 order-1 mb-3">
              <div
                className="uc-main panel"
                role="main"
                style={{ minHeight: "120vh" }}
              >
                <div className="panel vstack gap-3 lg:gap-4 xl:gap-5 mr-3">
                  <Gallery>
                    <div
                      className="post-content panel fs-6 md:fs-5 ml-2"
                      data-uc-lightbox="animation: scale"
                    >
                      <h2 className="h4 xl:h3 mt-4 mb-2 xl:mb-3">
                        Release of Google AI Overviews
                      </h2>
                      <p>
                        Google hosted its annual I/O developer conference last
                        Tuesday and introduced a series of artificial
                        intelligence products. These include new search and chat
                        features and AI hardware for cloud customers,
                        underlining Google’s insistence on AI even as rivals
                        like OpenAI emerge.
                      </p>
                      <h2 className="h4 xl:h3 mt-4 mb-2 xl:mb-3">
                        Transforming Search with AI Overviews
                      </h2>
                      <p className="mt-3">
                        The switch from traditional results based on links to
                        summaries generated by AI reveals a step towards a more
                        intuitive and integrated search experience. Many
                        industry experts have referred to this as the ‘day zero’
                        of Google search, the information retrieval technology
                        that makes it easy for users to get quick insights into
                        complex topics without having them move away from their
                        initial queries.
                      </p>
                      <p className="mt-3">
                        Generative AI significantly shifts from traditional
                        keyword-based searching towards more intuitive,
                        context-aware methods. It can generate and comprehend
                        text that sounds human-like, so users get a
                        comprehensive overview of their search queries
                        immediately.
                      </p>
                      <p className="mt-3">
                        With the help of Gemini, Google’s latest AI model, they
                        aim to revolutionize users’ interaction with search
                        results. To start, Google has introduced AI Overviews
                        (earlier Google SGE), which essentially provides a
                        summary of search results with links for further
                        details, transforming how users search for information
                        on Google.
                      </p>
                      <p className="mt-3">
                        Building on the capabilities introduced with SGE, Google
                        is pushing the boundaries of AI in search, making it
                        faster, more precise, and exceptionally user-friendly.
                        As AI Overviews roll out to users in the United States
                        with plans for global expansion, casual users and
                        professionals in fields like marketing should notice.
                      </p>
                      <h2 className="h4 xl:h3 mt-4 mb-2 xl:mb-3">
                        What Are Google’s AI Overviews?
                      </h2>
                      <p>
                        AI Overviews is a new Google search feature that uses
                        generative AI to create quick answers to search queries
                        through a topic preview with links to learn more.
                        Powered by Google Gemini, it combines information from
                        multiple online sources to save the searcher time and
                        provide a general overview – hence the name.
                      </p>
                      <h2 className="h4 xl:h3 mt-4 mb-2 xl:mb-3">
                        Example and Rollout
                      </h2>
                      <p className="mt-3">
                        As announced on May 14th, Google began rolling out AI
                        Overviews to US-based searchers, with plans to expand to
                        other countries. Originally introduced as part of the
                        Google Search Labs experiment, Search Generative
                        Experience (SGE), users had to opt into this feature. By
                        the end of 2024, AI Overviews will be available to over
                        a billion searchers.
                      </p>
                      <figure className="my-3 sm:my-4">
                        <Item
                          original="/assets/images/blog/internal/google-webpage.webp"
                          thumbnail="/assets/images/blog/internal/google-webpage.webp"
                          width="1280"
                          height="853"
                        >
                          {({ ref, open }) => (
                            <figure className="featured-image m-0 rounded ratio ratio-16x9 uc-transition-toggle overflow-hidden">
                              <Image
                                className="media-cover image uc-transition-scale-up uc-transition-opaque"
                                alt="Pink Marketing, by Mak"
                                src="/assets/images/blog/internal/google-webpage.webp"
                                width="1280"
                                height="853"
                                ref={ref}
                              />
                              <a
                                onClick={open}
                                className="position-cover"
                                data-caption="Pink Marketing, by Mak"
                              ></a>
                            </figure>
                          )}
                        </Item>
                      </figure>
                      <h2 className="h4 xl:h3 mt-4 mb-2 xl:mb-3">
                        How Do AI Overviews Work?
                      </h2>
                      <p>
                        Here’s a general model of how AI Overviews generate
                        responses:
                      </p>
                      <ul>
                        <li>
                          <b>Query Processing:</b>Once you type in a query, the
                          AI transforms your words into a vector, just as
                          ChatGPT works.
                        </li>
                        <li>
                          <b>Document Selection: </b>Google’s algorithm selects
                          a few relevant web pages containing information
                          related to the generated response.
                        </li>
                        <li>
                          <b>Fact-Checking: </b>These chosen documents act as
                          fact-checkers. If there is any contradiction between
                          the AI-generated text and the information provided in
                          these documents, then the AI modifies its response
                          accordingly. Hence, you can see the “sources”
                          mentioned each time.
                        </li>
                        <li>
                          <b>Evaluation:</b>An extra evaluation step might be
                          required to determine the response’s accuracy and
                          relevance before presenting it.
                        </li>
                      </ul>
                      <h2 className="h4 xl:h3 mt-4 mb-2 xl:mb-3">
                        The Impact of AI Overviews on SEO So Far
                      </h2>
                      <p className="mt-3">
                        At one point, an AI summary was produced by about 85% of
                        search queries. However, this trend has undoubtedly
                        reversed, and at present, approximately 14% of searches
                        produce an AI Summary. The likelihood of triggering an
                        AI summary varies considerably across domains,
                        fluctuating between 1% and 25%.
                      </p>
                      <h2 className="h4 xl:h3 mt-4 mb-2 xl:mb-3">
                        User Concerns
                      </h2>
                      <p>
                        Currently, users cannot opt out of AI Overviews, leading
                        to frustration among some who have flooded Google’s help
                        forums for advice on disabling them. The Google trends
                        chart for “turn off Google AI” spiked over the week that
                        AI Overviews were launched, highlighting widespread
                        discontent.
                      </p>
                      <p className="mt-3">
                        Given the scale of its release and the extensive amount
                        of Search Engine Results Page (“SERP”) real estate it
                        takes up, SEO professionals are concerned about how it
                        will impact their organic rankings and overall SEO
                        performance.
                      </p>
                      <h2 className="h4 xl:h3 mt-4 mb-2 xl:mb-3">
                        Concerns for Publishers
                      </h2>
                      <p>
                        Traditional page views may be adversely affected when AI
                        Overviews consolidate content, leading to decreased ad
                        revenue and lower content engagement. Based on habits
                        that emerged during the past year’s testing phase of
                        Google’s AI overviews, about 25% of the traffic could be
                        negatively affected by the de-emphasis on website links,
                        said Marc McCollum, chief innovation officer at Raptive.
                        <Link
                          className="text-blue"
                          href="https://apnews.com/article/google-search-ai-overviews-internet-traffic-ebb6bbbde17ed29a5f7b630d9e5e285b"
                          target="_blank"
                        >
                          (Source)
                        </Link>
                        {/* <a
                          className="text-blue"
                          href="https://apnews.com/article/google-search-ai-overviews-internet-traffic-ebb6bbbde17ed29a5f7b630d9e5e285b"
                          target="_blank"
                        >
                          (Source)
                        </a> */}
                      </p>
                      <h2 className="h4 xl:h3 mt-4 mb-2 xl:mb-3">
                        Transactional Keywords and Local Intent
                      </h2>
                      <p className="mt-3">
                        In some cases, AI Overviews may be seen for longer-tail
                        queries with transactional intent but only sometimes for
                        short-tail ones. AI Overviews no longer show for local
                        queries based on our sample. However, this might change
                        in the future.
                      </p>
                      <h2 className="h4 xl:h3 mt-4 mb-2 xl:mb-3">
                        Informational Keywords are Most Affected
                      </h2>
                      <p>
                        AI overviews are mainly triggered by informational
                        searches, especially those related to procedures or
                        tasks.
                      </p>
                      <h2 className="h4 xl:h3 mt-4 mb-2 xl:mb-3">
                        Authoritative Domains
                      </h2>
                      <p className="mt-3">
                        AI Overviews are available for authoritative domains
                        such as health, legal, and finance. However, they often
                        come with the recommendation to consult experts in the
                        field and to use the advice at the user’s own risk.
                      </p>
                      <h2 className="h4 xl:h3 mt-4 mb-2 xl:mb-3">
                        Why Are AI Overviews So Limited?
                      </h2>
                      <p>
                        The limited appearance of AI overviews suggests some
                        hesitation from Google in launching a full-scale
                        implementation. Potential reasons include:
                      </p>
                      <ul className="mt-2">
                        <li>
                          Intent mismatch between search queries and AI
                          Overviews.
                        </li>
                        <li>
                          Intent mismatch between search queries and AI
                          Overviews.
                        </li>
                        <li>
                          Fewer filters and features compared to traditional
                          search results.
                        </li>
                      </ul>
                      <h2 className="h4 xl:h3 mt-4 mb-2 xl:mb-3">
                        Embracing LLM SEO or Generative Engine Optimization
                      </h2>
                      <p>
                        LLM SEO / GEO revolves around content optimization for
                        generative engines, which makes it vital for any content
                        creator who desires to succeed in an AI-dominated search
                        scene. Content creators can significantly increase the
                        visibility of their content in artificial
                        intelligence-based searches by employing LLM SEO/GEO
                        strategies.
                      </p>
                      <p className="mt-3">
                        If you want to learn more about this topic, check out
                        the LLM SEO LeaderBoard. It covers almost all the
                        techniques and hacks that are currently available.
                      </p>
                      <h2 className="h4 xl:h3 mt-4 mb-2 xl:mb-3">
                        AI Monitor Tracker
                      </h2>
                      <p>
                        With AI Monitor, you can track how frequently your
                        content appears not only in AI overviews but also on
                        other platforms such as ChatGPT, Perplexity, and others.
                        After adding your website and setting up tracking for
                        your selected prompts, the tool will begin monitoring
                        your site’s visibility across nearly every LLM-powered
                        search engine.
                      </p>
                      <h2 className="h4 xl:h3 mt-4 mb-2 xl:mb-3">
                        Brand Mentions
                      </h2>
                      <p>
                        AI Monitor Brand Mentions is a fantastic tool for
                        tracking brand mentions in AI summaries across various
                        platforms. It’s like having a spotlight on your content,
                        even if it’s not ranking high traditionally.
                      </p>
                      <h2 className="h4 xl:h3 mt-4 mb-2 xl:mb-3">
                        AI Semantic Rating
                      </h2>
                      <p>
                        In addition to the above, we help marketers track
                        whether AI summaries portray your company as a hero or a
                        villain in a fairytale. AI Monitor analyzes sentiment in
                        AI summaries to ensure that your content is accurately
                        portrayed.
                      </p>
                      <h2 className="h4 xl:h3 mt-4 mb-2 xl:mb-3">
                        LLM Click Rate
                      </h2>
                      <p>
                        We have also invented a novel framework for analyzing
                        website prominence in AI summaries. Here, we present the
                        “LLM Click Rate (LCR)” score, which is based on several
                        significant metrics weighed by their importance in
                        showing the true exposure of the website within LSE
                        responses. You can learn more about this framework here.
                      </p>
                      <h2 className="h4 xl:h3 mt-4 mb-2 xl:mb-3">Conclusion</h2>
                      <p>
                        The key point is: don’t panic. Most AI responses are
                        aimed at less common, less searched-for queries, which
                        are generally unlikely to have a significant impact on
                        most sites.
                      </p>
                      <p className="mt-3"></p>
                      Why stress about your website’s SEO when you could
                      prioritize these vital queries for your site instead? If
                      you notice AI Overviews appearing for specific queries,
                      aim to become one of the featured sources.
                      <p className="mt-3">
                        If you want to learn more about how to feature your
                        content or brand on LLM-powered search engines, check
                        out the LLM SEO LeaderBoard, which covers almost all the
                        techniques and hacks known to mankind.
                      </p>
                      {/*  */}
                    </div>
                  </Gallery>
                </div>
              </div>
            </div>
            {/* <hr className="w-100 m-0 d-block mt-4 lg:mt-6 xl:mt-8 " /> */}
            <div className="lg:col-3 order-2 lg:order-0 sticky-element3 sm:mt-3">
              <AudioPlayer />
              <span className="">
                <TableOfContentsServer />
              </span>
            </div>
            <div className="lg:col-3 order-2 lg:order-2 sticky-element3">
              <RightSideTop />
              <RightSideBottom />
            </div>
            {/* <div className="d-block lg:d-none">
              <Toc />
            </div> */}
          </div>
          {/* <hr className="w-100 m-0 d-block mt-4 lg:mt-6 xl:mt-8" /> */}
          <div className="post-footer panel vstack sm:hstack gap-3 justify-between justifybetween border-top py-4 mt-4">
            <ul className="nav-x gap-narrow text-primary">
              <li>
                <span className="text-black dark:text-white me-narrow">
                  Tags:
                </span>
              </li>
              <li>
                <a href="#" className="gap-0">
                  Marketing
                  <span className="text-black dark:text-white">,</span>
                </a>
              </li>
              <li>
                <a href="#" className="gap-0">
                  Strategies
                  <span className="text-black dark:text-white">,</span>
                </a>
              </li>
              <li>
                <a href="#" className="gap-0">
                  Boost <span className="text-black dark:text-white">,</span>
                </a>
              </li>
              <li>
                <a href="#" className="gap-0">
                  Business
                </a>
              </li>
            </ul>
            <ul className="post-share-icons nav-x gap-narrow">
              <li className="me-1">
                <span className="text-black dark:text-white">Share:</span>
              </li>
              <li>
                <a
                  className="btn btn-md btn-outline-gray-100 w-32px lg:w-40px h-32px lg:h-40px text-dark dark:text-white dark:border-gray-600 hover:bg-primary hover:border-primary hover:text-white rounded-circle"
                  href="#"
                >
                  <i className="unicon-logo-facebook icon-1" />
                </a>
              </li>
              <li>
                <a
                  className="btn btn-md btn-outline-gray-100 w-32px lg:w-40px h-32px lg:h-40px text-dark dark:text-white dark:border-gray-600 hover:bg-primary hover:border-primary hover:text-white rounded-circle"
                  href="#"
                >
                  <i className="unicon-logo-x-filled icon-1" />
                </a>
              </li>
              <li>
                <a
                  className="btn btn-md btn-outline-gray-100 w-32px lg:w-40px h-32px lg:h-40px text-dark dark:text-white dark:border-gray-600 hover:bg-primary hover:border-primary hover:text-white rounded-circle"
                  href="#"
                >
                  <i className="unicon-email icon-1" />
                </a>
              </li>
              <li>
                <a
                  className="btn btn-md btn-outline-gray-100 w-32px lg:w-40px h-32px lg:h-40px text-dark dark:text-white dark:border-gray-600 hover:bg-primary hover:border-primary hover:text-white rounded-circle"
                  href="#"
                >
                  <i className="unicon-link icon-1" />
                </a>
              </li>
            </ul>
          </div>
        </div>
      </div>
    </div>
  );
}
