"use client";
import React from "react";
import Sidebar from "./sidebars/Sidebar";
import Image from "next/image";
import AudioPlayer from "./sidebars/AudioPlayer";
import TableOfContentsServer from "./sidebars/TableOfContentsServer";
import RightSideBottom from "./sidebars/RightSideBottom";
import RightSideTop from "./sidebars/RightSideTop";
import Toc from "./Toc";
import { Gallery, Item } from "react-photoswipe-gallery";

export default function ZeroClickSearches() {
  return (
    <div className="section panel mr-5">
      <div className="container container-full mx-3">
        <div className="panel py-4 lg:py-6 xl:py-8">
          <div className="row child-cols-12 ">
            <div className="sm:col-12 md:col-12 lg:col-6 order-1 mb-3">
              <div
                className="uc-main panel"
                role="main"
                style={{ minHeight: "120vh" }}
              >
                <div className="panel vstack gap-3 lg:gap-4 xl:gap-5 mr-3">
                  <Gallery>
                    <div
                      className="post-content panel fs-6 md:fs-5 ml-2"
                      data-uc-lightbox="animation: scale"
                    >
                      <h2 className="h4 xl:h3 mt-4 mb-2 xl:mb-3">
                        Introduction
                      </h2>
                      <p className="">
                        Ever searched something on Google and got the answer
                        right at the top, without even clicking a link? Welcome
                        to the zero click searches era, where Google zero click
                        searches dominate with quick fixes like featured
                        snippets, knowledge panels, and local packs. 60-65% of
                        Google searches ended without a click in 2024{" "}
                        <a
                          href="https://www.workshopdigital.com/blog/rise-in-zero-click-searches-deep-dive/"
                          target="_blank"
                          className="text-blue"
                        >
                          (Workshop Digital | Scrum Digital).
                        </a>
                      </p>
                      <p className="mt-3">
                        But here’s a twist: AI tools like ChatGPT are rewriting
                        the rules. Enter Generative Engine Optimization (GEO),
                        the new frontier where answers aren’t just pulled from
                        websites but generated by AI trained on mountains of
                        data. Unlike traditional SEO (which chases clicks), GEO
                        focuses on making your content so authoritative that AI
                        chatbots cite it verbatim. Think of it as SEO’s
                        AI-obsessed sibling: less about ranking #1 and more
                        about becoming the go-to source for complex queries like
                        “How do I fix a leaky faucet?” or “What’s the future of
                        AI in marketing?”
                      </p>
                      <p className="mt-3">
                        The kicker? While Google’s zero-click answers might cost
                        you short-term traffic, GEO offers indirect brand
                        exposure when AI name-drops your insights. But here’s
                        the catch: you’ll need to optimize heavily to survive
                        this AI-dominated future. Ready to crack the code of
                        zero-click dominance?
                      </p>
                      <p className="mt-3">
                        Let’s break down how this new world of zero-click
                        searches works, why it’s important for businesses and
                        content creators, and what you can do to adapt.
                      </p>
                      <h2 className="h4 xl:h3 mt-4 mb-2 xl:mb-3">
                        Zero-Click Searches: How Traditional SEO & Generative AI
                        Are Changing Search Behavior
                      </h2>
                      <figure className="my-3 sm:my-4">
                        <Item
                          original="/assets/images/blog/zero-click search-2-image.webp"
                          thumbnail="/assets/images/blog/zero-click search-2-image.webp"
                          width="1280"
                          height="853"
                        >
                          {({ ref, open }) => (
                            <figure className="featured-image m-0 rounded ratio ratio-16x9 uc-transition-toggle overflow-hidden">
                              <Image
                                className="media-cover image uc-transition-scale-up uc-transition-opaque"
                                alt="Pink Marketing, by Mak"
                                src="/assets/images/blog/zero-click search-2-image.webp"
                                width="1280"
                                height="853"
                                ref={ref}
                              />
                              <a
                                onClick={open}
                                className="position-cover"
                                data-caption="Pink Marketing, by Mak"
                              ></a>
                            </figure>
                          )}
                        </Item>
                      </figure>
                      <h3 className="h5 xl:h4 mt-3 mb-2 xl:mb-3">
                        What Are Zero-Click Searches?
                      </h3>
                      <p>
                        Zero-click searches occur when users get instant answers
                        directly on the search engine or AI platform—without
                        needing to click through to a website. This shift has
                        major implications for SEO, content strategy, and user
                        behavior.
                      </p>
                      <h3 className="h5 xl:h4 mt-3 mb-2 xl:mb-3">
                        1. Traditional Zero-Click Searches (Google & Classic
                        SEO)
                      </h3>
                      <p className="mt-3">
                        Search engines like Google have long provided quick
                        answers through:
                      </p>
                      <ul className="">
                        <li className="mt-1">
                          Featured Snippets – Concise responses to simple
                          queries (e.g., “What is the capital of France?”).
                        </li>
                        <li className="mt-1">
                          Knowledge Panels – Informational boxes for entities
                          (brands, celebrities, landmarks).
                        </li>
                        <li className="mt-1">
                          Local Packs – Instant business listings for “near me”
                          searches.
                        </li>
                      </ul>
                      <p className="mt-3">
                        The Catch? While these help users, they often reduce
                        website traffic since the answer appears right on the
                        SERP.
                      </p>
                      <h3 className="h5 xl:h4 mt-3 mb-2 xl:mb-3">
                        2. Generative AI Zero-Click Searches (ChatGPT, Gemini,
                        AI Overviews)
                      </h3>
                      <p>
                        AI-powered tools take this further by generating answers
                        instead of just curating them. Key differences:
                      </p>
                      <ul className="">
                        <li className="mt-1">
                          Dynamic Responses – AI doesn’t just pull a snippet; it
                          synthesizes information from its training data.
                        </li>
                        <li className="mt-1">
                          Complex Queries – Handles multi-part questions (e.g.,
                          “Explain quantum computing like I’m 5”).
                        </li>
                        <li className="mt-1">
                          Conversational Depth – Follow-up questions keep users
                          within the AI interface, eliminating the need for
                          external clicks entirely.
                        </li>
                      </ul>
                      <h3 className="h5 xl:h4 mt-3 mb-2 xl:mb-3">
                        The Big Shift:
                      </h3>
                      <h2 className="h4 xl:h3 mt-4 mb-2 xl:mb-3">
                        Capital of Texas3
                      </h2>
                      <ul className="">
                        <li className="mt-1">
                          Traditional SEO → Optimizing for rankings and featured
                          snippets.
                        </li>
                        <li className="mt-1">
                          Generative Engine Optimization (GEO) → Ensuring AI
                          tools cite and rely on your content for accurate,
                          up-to-date answers.
                        </li>
                      </ul>
                      <p className="mt-3 fw-bold">
                        The Future of Zero-Click: Blurring Lines Between Search
                        & AI
                      </p>
                      <p className="mt-3">
                        As Google integrates AI Overviews and chatbots dominate
                        complex queries, businesses must adapt by:
                      </p>
                      <p className="mt-3">
                        ✅ Structuring content for both featured snippets and AI
                        training data.
                      </p>
                      <p className="mt-3">
                        ✅ Focusing on authoritative, well-cited information to
                        be a trusted source for AI.
                      </p>
                      <p className="mt-3">
                        ✅ Exploring direct engagement strategies (e.g.,
                        chatbots, APIs) since organic traffic may decline.
                      </p>
                      <h3 className="h5 xl:h4 mt-3 mb-2 xl:mb-3">
                        So why does this matter?
                      </h3>

                      <p>
                        Well, the shift towards AI tools like ChatGPT is
                        massive. According to{" "}
                        <a
                          href="https://magecomp.com/blog/chatgpt-statistics/#:~:text=ChatGPT%20handles%20over%201%20billion%20queries%20per%20day%2C%20showcasing%20its%20robust%20infrastructure."
                          target="_blank"
                          className="text-blue"
                        >
                          MageComp,
                        </a>{" "}
                        ChatGPT handles over 1 billion queries per day. To put
                        that into perspective—if you take just 5 minutes to read
                        this blog, around 3.5 million people will have already
                        gotten their answers from ChatGPT in that same time.
                      </p>
                      <p className="mt-3">
                        Zero-click isn’t disappearing—it’s evolving. People love
                        the instant answers, and AI powered search engines and
                        chatbots are becoming a go-to for many search queries.
                        Winning in this new landscape means playing by the rules
                        of both traditional SEO and generative AI.
                      </p>
                      <h2 className="h4 xl:h3 mt-4 mb-2 xl:mb-3">
                        Why Zero-Click Searches Matter for Both SEO & GEO
                      </h2>
                      <p>
                        The rise of zero-click searches is reshaping digital
                        visibility—forcing businesses to rethink strategy across
                        both traditional search engines and generative AI
                        platforms. While this shift presents challenges for SEO,
                        it also unlocks new opportunities in GEO. Here’s how the
                        landscape is changing.
                      </p>
                      <h3 className="h5 xl:h4 mt-3 mb-2 xl:mb-3">
                        The SEO Challenge: Fewer Clicks, More Competition
                      </h3>
                      <p className="mt-3">
                        With Google’s featured snippets, knowledge panels, and
                        AI Overviews providing instant answers, users no longer
                        need to click through to websites for simple queries.
                        This trend has two major implications:
                      </p>
                      <ol className="">
                        <li className="mt-2">
                          Declining Organic Click-Through Rates (CTR)
                        </li>
                        <ul>
                          <li className="mt-1">
                            If users get answers directly on the SERP, why would
                            they visit your site?
                          </li>
                          <li className="mt-1">
                            Study from{" "}
                            <a
                              href="https://sparktoro.com/blog/2024-zero-click-search-study-for-every-1000-us-google-searches-only-374-clicks-go-to-the-open-web-in-the-eu-its-360/"
                              target="_blank"
                              className="text-blue"
                            >
                              SparkToro
                            </a>{" "}
                            show that nearly 60% of Google searches in the US
                            and EU were zero-click in 2024. A number that will
                            only grow as AI integrations expand.
                          </li>
                        </ul>

                        <li className="mt-2">
                          {" "}
                          Brand Authority vs. Lost Traffic
                        </li>
                        <ul>
                          <li className="mt-1">
                            While appearing in a featured snippet boosts
                            credibility, it doesn’t guarantee traffic.
                          </li>
                          <li className="mt-1">
                            As zero-click dominance grows, ranking #1 may no
                            longer be enough—you must also own the answer
                            directly on the SERP.
                          </li>
                        </ul>
                      </ol>
                      <h3 className="h5 xl:h4 mt-3 mb-2 xl:mb-3">
                        The GEO Opportunity: Brand Visibility Beyond Clicks
                      </h3>
                      <p>
                        Generative AI tools like ChatGPT, Gemini, and Perplexity
                        don’t just curate answers—they generate them. This
                        creates a new layer of exposure:
                      </p>
                      <p className="mt-2">
                        <b>Indirect Brand Recognition</b>
                      </p>
                      <ul>
                        <li className="mt-1">
                          Even if users don’t click, AI may cite your brand as a
                          source, reinforcing authority.
                        </li>
                        <li className="mt-1">
                          Example: If ChatGPT answers, “According to
                          [YourBrand], the best SEO strategy in 2024 is…”, you
                          gain visibility without a visit.
                        </li>
                      </ul>
                      <p className="mt-3">
                        <b>The Trust Factor</b>
                      </p>
                      <ul>
                        <li className="mt-1">
                          AI models prioritize well-structured, authoritative
                          sources.
                        </li>
                        <li className="mt-1">
                          By optimizing for GEO, you increase the chances of
                          being referenced—keeping your brand in the
                          conversation.
                        </li>
                      </ul>
                      <h2 className="h4 xl:h3 mt-4 mb-2 xl:mb-3">
                        Key Difference: SEO vs. GEO
                      </h2>
                      <div className="panel mt-2 p-2 border rounded-1-5 lg:rounded-2 dark:border-gray-600 dark:bg-black overflowx-auto">
                        <table className="uc-table uc-table-divider">
                          <thead className="table-head sticky-top z-1 ">
                            <tr className="table-row dark:border-white border-gray-900">
                              <th className="table-header-cell" scope="row">
                                <span className="fw-bold fs-5 lg:fs-4 dark:text-secondary">
                                  SEO (Search Engine Optimization)
                                </span>
                              </th>
                              <th className="table-header-cell" scope="row">
                                <span className="fw-bold fs-5 lg:fs-4 dark:text-secondary">
                                  GEO (Generative Engine Optimization)
                                </span>
                              </th>
                            </tr>
                          </thead>
                          <tbody className="table-body">
                            <tr className="table-row border-gray-900 dark:border-white">
                              <td>
                                <span className="dark:text-white">
                                  Goal: Drive traffic to your website.
                                </span>
                              </td>
                              <td>
                                <span className="dark:text-white">
                                  Goal: Ensure AI cites your content.
                                </span>
                              </td>
                            </tr>
                            <tr className="table-row border-gray-900 dark:border-white">
                              <td>
                                <span className="dark:text-white">
                                  Success = High rankings + clicks
                                </span>
                              </td>
                              <td>
                                <span className="dark:text-white">
                                  Success = Accurate AI references + brand
                                  mentions.
                                </span>
                              </td>
                            </tr>
                            <tr className="table-row border-gray-900 dark:border-white">
                              <td>
                                <span className="dark:text-white">
                                  Relies on Google’s algorithm.
                                </span>
                              </td>
                              <td>
                                <span className="dark:text-white">
                                  Depends on AI training data & real-time
                                  retrieval.
                                </span>
                              </td>
                            </tr>
                          </tbody>
                        </table>
                      </div>
                      <h3 className="h5 xl:h4 mt-3 mb-2 xl:mb-3">
                        The Hybrid Future: Optimizing for Both Worlds
                      </h3>
                      <p>
                        As users split searches between Google and AI chatbots,
                        businesses must adopt a dual strategy:
                      </p>
                      <ul>
                        <li className="mt-1">
                          <b>For SEO:</b> Structure content for featured
                          snippets, schema markup, and voice search.
                        </li>
                        <li className="mt-1">
                          <b>For GEO:</b> Focus on authoritative sourcing, clear
                          citations, and conversational formatting that AI can
                          easily extract.
                        </li>
                      </ul>
                      <p className="mt-3">
                        The brands that adapt fastest will stay visible, whether
                        their answers appear on Google’s SERP or ChatGPT’s
                        response box.
                      </p>
                      <h2 className="h4 xl:h3 mt-4 mb-2 xl:mb-3">
                        Impact of Zero-Click on SEO & Generative Engines
                      </h2>
                      <p>
                        Zero-click searches are changing how both traditional
                        SEO and generative engines operate. Here’s how each is
                        affected:
                      </p>
                      <h3 className="h5 xl:h4 mt-3 mb-2 xl:mb-3">
                        Impact on Traditional SEO
                      </h3>
                      <ul>
                        <li className="mt-2">
                          <b>User Intent Over Keywords:</b> Google is
                          increasingly focusing on user intent. It’s not just
                          about keywords anymore—Google wants to understand what
                          people are actually looking for.
                        </li>
                        <li className="mt-2">
                          <b>
                            Reduced Organic Traffic for Informational Queries:
                          </b>{" "}
                          Traditional SEO relied on ranking highly to drive
                          clicks, but zero-click features like featured
                          snippets, knowledge panels, or “People Also Ask” boxes
                          provide instant answers.
                        </li>
                      </ul>
                      <h3 className="h5 xl:h4 mt-3 mb-2 xl:mb-3">
                        Impact on Generative Engines (GEO)
                      </h3>
                      <ul>
                        <li className="mt-2">
                          <b>
                            Brand Authority and Source Attribution Become
                            Critical:
                          </b>
                          Generative AI often cites or paraphrases trusted
                          sources (e.g., government sites, academic journals,
                          established brands).
                        </li>
                        <li className="mt-2">
                          <b>
                            Rise of Conversational and Long-Tail Keyword
                            Targeting:
                          </b>
                          Users interact with generative engines using natural
                          language (e.g., “Explain quantum computing in simple
                          terms”).
                        </li>
                      </ul>
                      <h2 className="h4 xl:h3 mt-4 mb-2 xl:mb-3">
                        Does Zero-Click Increase Traffic? The Reality
                      </h2>
                      <figure className="my-3 sm:my-4">
                        <Item
                          original="/assets/images/blog/zero-click search-3-image.webp"
                          thumbnail="/assets/images/blog/zero-click search-3-image.webp"
                          width="1280"
                          height="853"
                        >
                          {({ ref, open }) => (
                            <figure className="featured-image m-0 rounded ratio ratio-16x9 uc-transition-toggle overflow-hidden">
                              <Image
                                className="media-cover image uc-transition-scale-up uc-transition-opaque"
                                alt=""
                                src="/assets/images/blog/zero-click search-3-image.webp"
                                width="1280"
                                height="853"
                                ref={ref}
                              />
                              <a
                                onClick={open}
                                className="position-cover"
                                data-caption=""
                              ></a>
                            </figure>
                          )}
                        </Item>
                      </figure>
                      <p className="mt-3">
                        So, does zero-click lead to more traffic? Well, it’s a
                        bit of a mixed bag.
                      </p>
                      <ul className="">
                        <li className="mt-1">
                          <b>Short-Term Traffic Loss:</b>
                          Since users can get the answer directly from Google,
                          they might not click through to your website.
                        </li>
                        <li className="mt-1">
                          <b>Long-Term Authority Gains:</b>
                          But appearing in a featured snippet or answer box can
                          increase your brand’s authority. Users might search
                          for your brand specifically later on, driving more
                          traffic to your site.
                        </li>
                        <li className="mt-1">
                          For generative engines, traffic is a bit trickier. It
                          depends on whether the AI tool credits your website or
                          brand. Some AI tools, like Perplexity.ai, include
                          source links, but tools like ChatGPT don’t unless
                          plugins are used.
                        </li>
                      </ul>
                      <h3 className="h5 xl:h4 mt-3 mb-2 xl:mb-3">
                        Actionable Insight to make your site AI Crush
                      </h3>
                      <p>
                        Instead of focusing on clicks, think about building
                        brand trust. If AI tools see your brand as an
                        authoritative source, it will pay off in the long run.
                      </p>
                      <h2 className="h4 xl:h3 mt-4 mb-2 xl:mb-3">
                        How to Optimize for Zero-Click (SEO + GEO)
                      </h2>
                      <p className="mt-3">
                        To succeed in this new world, you’ll need to optimize
                        for both traditional SEO and generative engine
                        optimization. Here are some practical tips:
                      </p>
                      <h3 className="h5 xl:h4 mt-3 mb-2 xl:mb-3">
                        A. Traditional SEO Tactics
                      </h3>
                      <ul>
                        <li className="mt-2">
                          <b>Mobile Optimization:</b> Mobile zero-click rates
                          hit 75%, demanding mobile-first optimization(Conductor
                          | Scrum Digital), so ensure your site is
                          mobile-friendly.
                        </li>
                        <li className="mt-2">
                          <b>Use Snippet-Friendly Formatting:</b> Use bullet
                          points, numbered lists, and headers (H2/H3) to
                          increase your chances of showing up in featured
                          snippets.
                        </li>
                      </ul>
                      <p className="mt-3">
                        <b>Voice Search Optimization:</b> Many voice searches
                        are question-based, so optimize your content to sound
                        natural and conversational.
                      </p>
                      <h3 className="h5 xl:h4 mt-3 mb-2 xl:mb-3">
                        B. Generative Engine Optimization (GEO) Tactics
                      </h3>
                      <ul>
                        <li className="mt-2">
                          <b>Target Question-Based Keywords:</b> Focus on
                          long-tail keywords that reflect how people phrase
                          their questions, like “What is the best tool for X?”.
                        </li>
                        <li className="mt-2">
                          <b>Write In-Depth Guides:</b> AI tools love
                          well-structured, step-by-step guides. The clearer your
                          content, the more likely it is to be cited by AI.
                        </li>
                        <li className="mt-2">
                          <b>Content Quality:</b> Publish original research,
                          case studies, and data-driven insights. AI tools
                          prioritize credible sources, so the better your
                          content, the more likely it is to be used.
                        </li>
                        <li className="mt-2">
                          <b>Boosts AI Trustworthiness:</b> Search engines and
                          AI models prioritize content from reliable sources,
                          enhancing visibility and ranking within Generative
                          Engine Optimization (GEO).
                        </li>
                      </ul>
                      <p className="mt-3">
                        <b>Schema Markup: </b> Use schema markup to help AI
                        understand your content’s context, making it easier for
                        them to generate accurate answers.
                      </p>
                      <h4 className="h6 xl:h5 mt-2 mb-2 xl:mb-3">
                        Authority Signals
                      </h4>
                      <ul>
                        <li className="mt-2">
                          <b>Earn Backlinks:</b>Backlinks and citations from
                          high-authority websites and publication houses signal
                          trustworthiness, which AI tools value.
                        </li>
                        <li className="mt-2">
                          <b>E-E-A-T:</b> Make sure your content reflects
                          Experience, Expertise, Authoritativeness, and
                          Trustworthiness to gain AI’s trust.
                        </li>
                        <li className="mt-2">
                          <b>Use Reddit & Quora: </b> Reddit and Quora boost
                          zero-click search by providing conversational Q&A
                          content that matches natural language queries, feeding
                          featured snippets and AI answers.
                        </li>
                      </ul>
                      <h2 className="h4 xl:h3 mt-4 mb-2 xl:mb-3">Conclusion</h2>
                      <p>
                        So, here’s the tea: Zero-click searches aren’t going
                        anywhere, whether you’re battling Google’s snippets or
                        AI’s auto-generated essays. Traditional SEO? It’s like
                        playing a game of chess with Google, where clicks are
                        your checkmate. But GEO? That’s the wildcard, where
                        being quoted by a chatbot is the new flex.
                      </p>
                      <p className="mt-3">
                        You can’t put all your eggs in one basket. Double down
                        on zero-click searches and cozy up to GEO by creating
                        content so sharp, even AI can’t resist name-dropping
                        you. After all, why choose between traffic and authority
                        when you can have both?
                      </p>
                      <p className="mt-3">
                        Future-proof your strategy, stay ahead of the
                        algorithms, and remember: in a world where answers come
                        before clicks, being the source is the ultimate win. Now
                        is the time to start working to make Google and ChatGPT
                        your biggest fans. 🚀
                      </p>
                      {/*  */}
                    </div>
                  </Gallery>
                </div>
              </div>
            </div>
            {/* <hr className="w-100 m-0 d-block mt-4 lg:mt-6 xl:mt-8 " /> */}
            <div className="lg:col-3 order-2 lg:order-0 sticky-element3 sm:mt-3">
              <AudioPlayer />
              <span className="">
                <TableOfContentsServer />
              </span>
            </div>
            <div className="d-none lg:d-block lg:col-3 order-2 lg:order-2 sticky-element3">
              <RightSideTop />
              <RightSideBottom />
            </div>
            {/* <div className="d-block lg:d-none">
              <Toc />
            </div> */}
          </div>
          {/* <hr className="w-100 m-0 d-block mt-4 lg:mt-6 xl:mt-8" /> */}
          <div className="post-footer panel vstack sm:hstack gap-3 justify-between justifybetween border-top py-4 mt-4">
            <ul className="nav-x gap-narrow text-primary">
              <li>
                <span className="text-black dark:text-white me-narrow">
                  Tags:
                </span>
              </li>
              <li>
                <a href="#" className="gap-0">
                  Marketing
                  <span className="text-black dark:text-white">,</span>
                </a>
              </li>
              <li>
                <a href="#" className="gap-0">
                  Strategies
                  <span className="text-black dark:text-white">,</span>
                </a>
              </li>
              <li>
                <a href="#" className="gap-0">
                  Boost <span className="text-black dark:text-white">,</span>
                </a>
              </li>
              <li>
                <a href="#" className="gap-0">
                  Business
                </a>
              </li>
            </ul>
            <ul className="post-share-icons nav-x gap-narrow">
              <li className="me-1">
                <span className="text-black dark:text-white">Share:</span>
              </li>
              <li>
                <a
                  className="btn btn-md btn-outline-gray-100 w-32px lg:w-40px h-32px lg:h-40px text-dark dark:text-white dark:border-gray-600 hover:bg-primary hover:border-primary hover:text-white rounded-circle"
                  href="#"
                >
                  <i className="unicon-logo-facebook icon-1" />
                </a>
              </li>
              <li>
                <a
                  className="btn btn-md btn-outline-gray-100 w-32px lg:w-40px h-32px lg:h-40px text-dark dark:text-white dark:border-gray-600 hover:bg-primary hover:border-primary hover:text-white rounded-circle"
                  href="#"
                >
                  <i className="unicon-logo-x-filled icon-1" />
                </a>
              </li>
              <li>
                <a
                  className="btn btn-md btn-outline-gray-100 w-32px lg:w-40px h-32px lg:h-40px text-dark dark:text-white dark:border-gray-600 hover:bg-primary hover:border-primary hover:text-white rounded-circle"
                  href="#"
                >
                  <i className="unicon-email icon-1" />
                </a>
              </li>
              <li>
                <a
                  className="btn btn-md btn-outline-gray-100 w-32px lg:w-40px h-32px lg:h-40px text-dark dark:text-white dark:border-gray-600 hover:bg-primary hover:border-primary hover:text-white rounded-circle"
                  href="#"
                >
                  <i className="unicon-link icon-1" />
                </a>
              </li>
            </ul>
          </div>
        </div>
      </div>
    </div>
  );
}
